services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  channel:
    image: redis:latest
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

